// <auto-generated> 请勿修改 </auto-generated>
using System;
using System.Collections.Generic;

namespace Suplike.Config
{
    [Serializable]
    public class TestConfig : IConfigWithId
    {
        /// <summary>
        /// ID
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 浮点数
        /// </summary>
        public float FVal;

        /// <summary>
        /// 双精度
        /// </summary>
        public double DVal;

        /// <summary>
        /// 布尔值
        /// </summary>
        public bool BoolVal;

        /// <summary>
        /// 布尔数
        /// </summary>
        public bool BVal;

        /// <summary>
        /// 整数列表
        /// </summary>
        public List<int> IntList;

        /// <summary>
        /// 字串列表
        /// </summary>
        public List<string> StrList;

        /// <summary>
        /// 字典
        /// </summary>
        public Dictionary<int,string> Dic;

        /// <summary>
        /// 信息内容
        /// </summary>
        public string Content;

    }
}
