// <auto-generated> 请勿修改 </auto-generated>
using System;
using System.Collections.Generic;
namespace Suplike.Config
{
    [Serializable]
    public class TestConfig
    {
        //ID
        public int Id;
        //浮点数
        public float FVal;
        //双精度
        public double DVal;
        //布尔值
        public bool BoolVal;
        //布尔数
        public bool BVal;
        //整数列表
        public List<int> IntList;
        //字串列表
        public List<string> StrList;
        //字典
        public Dictionary<int,string> Dic;
        //信息内容
        public string Content;
    }
}
